### ISSUE TITLE
arm64 macOS builds are really x86_64

### ISSUE THREAD

**Issue by kcoul** [csukuangfj/onnxruntime-libs#11]
`lipo -info ./macos-arm64/libonnxruntime.a`
`Non-fat file: ./macos-arm64/libonnxruntime.a is architecture: x86_64`

**Comment by kcoul** [comment]
The universal builds do however seem to have arm64

**Comment by csukuangfj** [comment]
<img width="1262" alt="Screenshot 2024-03-02 at 08 22 33" src="https://github.com/csukuangfj/onnxruntime-libs/assets/5284924/d5f59e33-8aad-415e-86e6-ca4bafadf4c5">


```
(py38) fangjuns-MacBook-Pro:Downloads fangjun$ lipo -info onnxruntime-osx-arm64-static_lib-1.17.1/lib/libonnxruntime.a
Non-fat file: onnxruntime-osx-arm64-static_lib-1.17.1/lib/libonnxruntime.a is architecture: arm64
```

By the way, where did you get your lib? It shows arm64 on my side.

**Comment by csukuangfj** [comment]
Closing as no response has been received for a long time.
