### ISSUE TITLE
Can you provide a library version compiled with MD under MSVC?

### ISSUE THREAD

**Issue by kubiwudi** [csukuangfj/onnxruntime-libs#16]
only find MT lib

**Comment by csukuangfj** [comment]
Please complile it by yourself.

**Comment by csukuangfj** [comment]
please see
https://github.com/csukuangfj/onnxruntime-build/pull/24

**Comment by csukuangfj** [comment]
静态库，动态库，都支持 MD, MT 了。请看 https://github.com/csukuangfj/onnxruntime-libs/releases/tag/v1.23.2
