### ISSUE TITLE
Add Windows x64 debug build

### ISSUE THREAD

**Issue by thewh1teagle** [csukuangfj/onnxruntime-libs#19]
Currently [onnxruntime-win-x64-static-debug.cmake#L18](https://github.com/k2-fsa/sherpa-onnx/blob/master/cmake/onnxruntime-win-x64-static-debug.cmake#L18) points to non existent build on this repo. I think you need to trigger debug build for it.

**Comment by csukuangfj** [comment]
Please see
https://github.com/csukuangfj/onnxruntime-build/actions/workflows/windows-x64-debug.yaml
