### ISSUE TITLE
能否提供 MD 版本

### ISSUE THREAD

**Issue by endink** [csukuangfj/onnxruntime-libs#31]
windows 现在都是 MT，打包 CRT 不是好主意啊，能否提供  MD 的静态库， 这个项目真的很方便啊

**Comment by csukuangfj** [comment]
MD 里的 d , 就是dynamic 的意思，对不对？

我们没有 md 的静态库.

**Comment by endink** [comment]
我说的不是动态库，静态库现在编译的链接了 MSVCRT.lib 静态库（MT），使用 `/MT` 选项也不是微软推荐的方式呀，我的意思是静态库不去链接 MSVC 运行时，而是使用操作系统的 dll。   

现在提供的库应该做 Static MT,  我像问的是能否提供 Static MD 的库。   

https://learn.microsoft.com/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170

**Comment by csukuangfj** [comment]
我们没目前没有。你需要自己去看代码，看如何编译。

**Comment by csukuangfj** [comment]
我们现在提供的库，方便用户链接和部署。你要的这个，用户用起来，容易报错

**Comment by endink** [comment]
行吧，那 fork 一下你的 repo 算了，其实一样的，CRT 只要 MSVC 不低于编译版本都不会出错的, 这东西操作系统都自动更新了，静态链接 CRT 以后，如果开发时候想去链接一个动态库，基本都没法了，要求所有依赖都是静态库太难了，版本冲突那么多，因为动态库都是 /MD 编译的，我看了 onnx project 那个 `build.py` 其实就是现在的 github action 里加了 `enable_msvc_static_runtime `, 我觉得多提供一套也可以, 不提供只能 fork 你的改了

**Comment by csukuangfj** [comment]
那如果我们提供的话，你帮忙测试？

**Comment by lin-name** [comment]
很好的建议，请问您目前有 MD 的静态库了吗？或者可以编译的源码的链接？有的话方便提供一下，多谢啦

**Comment by endink** [comment]
@lin-name 你可以在我的仓库下载， 希望可以刚到你。   

https://github.com/endink/onnxruntime-build/releases

**Comment by csukuangfj** [comment]
请看

https://github.com/csukuangfj/onnxruntime-build/pull/24

正在修改动态库 (onnxruntime.dll), 也支持这个.

**Comment by csukuangfj** [comment]
静态库，动态库，都支持 MD, MT 了。请看 https://github.com/csukuangfj/onnxruntime-libs/releases/tag/v1.23.2
