### ISSUE TITLE
Hello, does this project have source code?

### ISSUE THREAD

**Issue by nmanhong** [csukuangfj/onnxruntime-libs#9]
I need to compile the source code. After I compiled onnxruntime, there are no such .so

**Comment by csukuangfj** [comment]
The source code is in https://github.com/csukuangfj/onnxruntime-libs/tree/master/.github/workflows

**Comment by abdullahaygun** [comment]
> The source code is in https://github.com/csukuangfj/onnxruntime-libs/tree/master/.github/workflows


When I ran the yml file you showed (the one for Linux), it only extracted shared objects because "--build_shared_lib" was active during build. Are you sure this yml file is correct?

**Comment by csukuangfj** [comment]
Which yml file are you running?

And what generated files do you want?

**Comment by abdullahaygun** [comment]
> Which yml file are you running?
> 
> And what generated files do you want?


I tried to create a static onnxruntime build for x86_64 by examining the codes in the arm-linux-gnueabihf.yaml file, but it did not work. On another topic([https://github.com/microsoft/onnxruntime/issues/15032#issuecomment-1470752500](https://github.com/microsoft/onnxruntime/issues/15032#issuecomment-1470752500)), I tried to combine the statically built module into a single file, but it did not work. Can you help?

**Comment by csukuangfj** [comment]
> I tried to create a static onnxruntime build for x86_64

In that case, you should have a look at
https://github.com/csukuangfj/onnxruntime-libs/tree/master/.github/workflows


---

You were asking the source code of this repo, that is why you were directed to the .github/workflows in this repo.

Had you asked earlier for building static libs for windows, would I point you directly to
https://github.com/csukuangfj/onnxruntime-libs/tree/master/.github/workflows

**Comment by csukuangfj** [comment]
Note that I have edited URL in the above comment to
https://github.com/csukuangfj/onnxruntime-build/tree/master/.github/workflows
